### PR TITLE
PT-2862: The order of the proband parents should ALWAYS be father-left mother-right

### PR DESCRIPTION
**Pull request by allasm**

### CODE REVIEW

**Comment by sashaandjic** [comment]
importing pedigree of the family from the playground https://playground.phenotips.org/edit/Families/FAM0001045sheet=PhenoTips.PedigreeEditor&action=view
places mother and father of the proband in the wrong order

**Comment by sashaandjic** [comment]
automatic layout doesn't correct this simple pedigree
screen shot 2017-03-11 at 12 40 46 am

**Comment by marta-** [comment]
@sashaandjic : @allasm has made some changes, can you please re-test before noon tomorrow? Thanks!

**Comment by sashaandjic** [comment]
@marta- I'm on it.

**Comment by sashaandjic** [comment]
tested. no problems found.

**Pull request merged**
