### PR TITLE
Issue #1624: Added a pedigree print dialog/ability to print pedigrees.

### PR DESCRIPTION
**Pull request by allasm**
Also fixes visible editor-mode only symbols (e.g. node shading) visible in saved pedigree images.

### CODE REVIEW

**Comment by sdumitriu** [comment]
Pedigree menu looks completely broken:
1624-broken-menu

**Comment by allasm** [comment]
It is not for me - I saw it happened once before, and was fixed after a refresh, seems to be caching issue. Is it still broken after a refresh?

**Comment by sdumitriu** [comment]
Yes, still broken.

**Comment by sdumitriu** [comment]
Menu is now fixed. Other issues:

- [ ] Sometimes when there's an arched connection between two nodes on the top row, it doesn't get printed (see attached)
- [ ] The landscape mode isn't supported on FF 38.2.1 ESR / Linux, so the pages have too much extra white space at the bottom
- [ ] "slightly overlapped" is probably too slightly, there's almost no difference with or without that option
- [ ] There should be a smarter way to split the image, right now it just cuts nodes in half, along with any text it may have. But this is a difficult problem, it can wait for a future version.

[ped.pdf](https://github.com/phenotips/phenotips/files/2855/ped.pdf)

**Comment by allasm** [comment]
1) Will check

2) There is no way to force FF to use landscape mode programmatically ([known missing feature](https://bugzilla.mozilla.org/show_bug.cgi?id=851441)). I should probably add an option to print in portrait, but generally users are supposed to manually set landscape mode in FF's print dialogue before printing

3) overlap is about 0.5 centimeters when printed - the idea that should be enough to overlap/glue pages together. Need to ask Courtney again if this is needed.

4) I though about this, this is hard and in general case there may be no perfect split. My idea was that by enlarging/shrinking by 10% you can get a better fit manually. Not sure if manual left-right shift controls are useful. Overlaps may help as well to mitigate this problem.

**Comment by allasm** [comment]
#1 is fixed.
#2 unfixable, made warning about manually selecting correct orientation more prominent
#3 increased overlap slightly
#4 added manual controls so that users can move the pedigree slightly for best split between the pages

**Comment by sdumitriu** [comment]
Why was this closed?

**Comment by sdumitriu** [comment]
The top is correctly printed, but now the bottom is cropped:
cropped-bottom

**Comment by allasm** [comment]
Fixed. I will improve page splitting more significantly for 1.3, but this should work for now.

**Comment by allasm** [comment]
Rebased on top of current master, updated for require.js and did a smoke test - ready to be merged

**Pull request merged**
