### PR TITLE
PT-2435: Use underscores rather than spaces in pedigree export filenames.

### PR DESCRIPTION
**Pull request by veronikaslc**
Fixed.

### CODE REVIEW

**Comment by veronikaslc** [comment]
@itaiGershtansky @mjshepherd please, review

**Comment by itaiGershtansky** [comment]
+1

**Comment by buske** [comment]
You've got a stray whitespace change in the diff that could be committed straight to master and shouldn't really be part of the PR, but other than that +1.

**Comment by mjshepherd** [comment]
+1

**Pull request merged**
