### PR TITLE
[misc] alignment of '+' signs in buttons of gene-variant section

### PR DESCRIPTION
**Pull request by veronikaslc**
Poor alignment of '+' signs in Add variant and Add gene buttons

### CODE REVIEW

**Comment by veronikaslc** [comment]
@itaiGershtansky @buske please review :) If I may assign Orion, because he reported.

**Comment by buske** [comment]
@veronikaslc Sure! I'll try to test this out tomorrow. :)

**Comment by buske** [comment]
Looks good to me! +1

**Comment by itaiGershtansky** [comment]
+1 as well.

**Comment by veronikaslc** [comment]
Ready for merge? :)

**Pull request merged**
