### PR TITLE
PT-3624: Upgrade XWiki to 7.4.6

### PR DESCRIPTION
**Pull request by sdumitriu**

### CODE REVIEW

**Comment by sdumitriu** [comment]
@sashaandjic That build problem is now fixed.

**Comment by sashaandjic** [comment]
@sdumitriu 
it fails again
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project patient-data-pageobjects: Compilation failure: Compilation failure:
[ERROR] /Users/sasha/Documents/PT/phenotips/components/patient-data/pageobjects/src/main/java/org/phenotips/data/test/po/PatientRecordViewPage.java:[635,25] cannot find symbol
[ERROR] symbol:   method hasElement(org.openqa.selenium.By)
[ERROR] location: class org.xwiki.test.ui.TestUtils
[ERROR] /Users/sasha/Documents/PT/phenotips/components/patient-data/pageobjects/src/main/java/org/phenotips/data/test/po/PatientRecordEditPage.java:[1146,13] cannot find symbol
[ERROR] symbol:   method findElementWithoutWaiting(org.xwiki.test.ui.XWikiWebDriver,org.openqa.selenium.By)
[ERROR] location: class org.xwiki.test.ui.TestUtils
[ERROR] /Users/sasha/Documents/PT/phenotips/components/patient-data/pageobjects/src/main/java/org/phenotips/data/test/po/PatientRecordEditPage.java:[1851,17] cannot find symbol
[ERROR] symbol:   method hasElement(org.openqa.selenium.By)
[ERROR] location: class org.xwiki.test.ui.TestUtils
[ERROR] /Users/sasha/Documents/PT/phenotips/components/patient-data/pageobjects/src/main/java/org/phenotips/data/test/po/PatientRecordEditPage.java:[1870,17] cannot find symbol
[ERROR] symbol:   method hasElement(org.openqa.selenium.By)
[ERROR] location: class org.xwiki.test.ui.TestUtils
[ERROR] /Users/sasha/Documents/PT/phenotips/components/patient-data/pageobjects/src/main/java/org/phenotips/data/test/po/PatientRecordEditPage.java:[1889,17] cannot find symbol
[ERROR] symbol:   method hasElement(org.openqa.selenium.By)
[ERROR] location: class org.xwiki.test.ui.TestUtils
[ERROR] -> [Help 1]

**Comment by sdumitriu** [comment]
@sashaandjic That is also fixed now.

**Comment by danielpgross** [comment]
I've finished a first round of testing (of both the UI and REST APIs) and have not found any problems so far.

**Comment by marta-** [comment]
Let's merge this in 1.4-m4.

**Comment by sdumitriu** [comment]
@sashaandjic Any update on this?

**Comment by sashaandjic** [comment]
I think it is ok.

**Comment by sebialex** [comment]
Sorry, I forgot to post the review. I looked at it a while ago. Looked good to me.

**Pull request merged**
