### PR TITLE
PT-3359: Replace "Patient" with "PrimaryEntity" in the permissions module

### PR DESCRIPTION
**Pull request by a-gvo**

### CODE REVIEW

**Comment by a-gvo** [comment]
First 5 commits are from PT-3409.

**Comment by a-gvo** [comment]
Rebased on top of PT-3441.

**Comment by sashaandjic** [comment]
Found the following problem. I have a family whose 2 members were created by Peter, and one by Mary. Mary transferred the ownership of patient that she created to Peter. If Peter opens this patient by opening Family page and clicking on the link within pedigree editor thumbnail, the patient record form opens properly, however when Peter closes it instead of going back to the Family page he gets an error message stating that the record is locked by Mary.

**Comment by a-gvo** [comment]
Rebased with latest master.

**Comment by sashaandjic** [comment]
Ok. I will log this asa separate issue. I haven't found any other issue.

**Pull request merged**
