### PR TITLE
PT-3646: Validate entered PubMed ID

### PR DESCRIPTION
**Pull request by veronikaslc**

### CODE REVIEW

**Comment by veronikaslc** [comment]
@sashaandjic For testing you can enter `24706940` in pubmed ID field, expected info from this article:
https://www.ncbi.nlm.nih.gov/pubmed/?term=24706940
or enter any letters, extected `invalid` message

**Comment by sashaandjic** [comment]
just a small ui correction is needed. 4 headings (AGE OF ONSET, MODE OF...) seem to not be centered.

**Comment by veronikaslc** [comment]
@sashaandjic I think last comment is for PN? (for this commit-> https://github.com/phenotips/patient-network/pull/189/commits/84f8d61ff16c51ce6805ed1f4056a7b8d2f1f6f0 )

**Comment by sashaandjic** [comment]
@veronikaslc Yes.

**Comment by sashaandjic** [comment]
@veronikaslc 
screen shot 2018-04-03 at 6 31 38 pm

**Comment by veronikaslc** [comment]
@sashaandjic  fixed

**Comment by sashaandjic** [comment]
It would be nice to preserve the publication details in view mode and when clicking on PubMed field.

**Comment by sashaandjic** [comment]
When marking a case resolved, we should warn user to mark appropriate genes as confirmed causal (in case there are none).

**Comment by veronikaslc** [comment]
We need @marta-'s review here

**Comment by sashaandjic** [comment]
tested! looks good.

**Comment by veronikaslc** [comment]
tested in browsers: Chrom, Safari, FireFox, worked too.

**Comment by veronikaslc** [comment]
@sdumitriu reproduced the issue, it has to be numerical invalid input, fixed now.

**Comment by veronikaslc** [comment]
@sdumitriu codereview comments addressed

**Comment by veronikaslc** [comment]
@sdumitriu done

**Pull request merged**
