### PR TITLE
[bugfix] Small UI fix: the global tools menu entries are misaligned vertically

### PR DESCRIPTION
**Pull request by sdumitriu**
Before:
image

After:
image

### CODE REVIEW

**Comment by sdumitriu** [comment]
@sashaandjic @veronikaslc When testing this, please test in as many browsers you can.

**Comment by marta-** [comment]
+1. Tested in FF & Chrome.

**Comment by sashaandjic** [comment]
mac: Chrome & Safari Create..., New patient, New family menu options are not aligned to the left. In Safari the misalignment is more prominent

**Comment by marta-** [comment]
@sashaandjic can you provide screenshots? thanks.

**Comment by marta-** [comment]
@sashaandjic Is this an issue introduced by the fix? What do the playground.phenotips.org menus look like on Mac in Chrome & Safari?

**Comment by sashaandjic** [comment]
@marta- no the issue was not introduced by this fix

**Comment by veronikaslc** [comment]
Tested in IE / Chrome / Safari / Mozilla FF

**Comment by veronikaslc** [comment]
Sorry! I intended to approve only first part. Second is fix makes stuff better, but there are still  some imperfections.
In Chrome and Safary

**Comment by veronikaslc** [comment]
In IE / Chrome / Mozilla FF

**Comment by marta-** [comment]
@veronikaslc can you confirm the issues you described were caused by these changes and were not present previously?

**Comment by veronikaslc** [comment]
Sure. Just one more
In IE and Mozilla FF

**Comment by veronikaslc** [comment]
Disregard other two, just one issue above. Seems, it is introduced by [this line](https://github.com/phenotips/phenotips/commit/29202c67fdd7c7f34698276d4cc2bbb9c7067c1c#diff-f340ce5ed903559b592dabd003f150e3R964)

**Pull request merged**
