### PR TITLE
Support for family members without a pedigree node

### PR DESCRIPTION
**Pull request by allasm**

### CODE REVIEW

**Comment by allasm** [comment]
@sashaandjic: right now this pull request only has PT-3513, but since PT-3513 is required for PT-3379 (arguably a more important issue) this PR will be updated to include PT-3379 as well. But for now PT-3513 can/should be tested as a standalone PR

**Comment by sashaandjic** [comment]
@allasm I think this PR is fine.

**Comment by allasm** [comment]
Note: this should not be merged yet, until one more JIRA issue makes it to the PR

**Comment by sashaandjic** [comment]
Problem found:
1. create simple family with one patient who has phenotypes,genotypes and diagnosis
2. open pedigree editor and unlink patient without clearing data from the node
3. assign the patient to a free node
4. click on the original node (coloured but no patient assigned) and click "Create new" butto
5. it appears as the new patient was created with all phenotypes,genotypes and diseases; SAVE
6. go to the newly created patient and observe that the record is empty ( no phenotyes, genotypes and diseases, nor pedigree)
7. open the family pedigree again and notice to identical nodes with the same PatientID
step 1
step 2
step 3
step 4
step 5
step 6
step 7

**Comment by sashaandjic** [comment]
Problem found:

- create simple family (mother, father, child) with one patient who has phenotypes,genotypes and diagnosis
- open pedigree editor and unlink patient without clearing data from the node
- assign unlinked patient to a free node
- click on the original node (coloured but no patient assigned) and click "Create new" bttn

The new patient was created; all colours as replaced with orange (marked as affected), without any phenotypes,genotypes and diseases.
Expected behaviour: The new patient was supposed to have phenotype, gene and diagnosis

**Pull request merged**
