### PR TITLE
Minor pedigree UI fixes (PT-2248, PT-2254, PT-2255, PT-2265)

### PR DESCRIPTION
**Pull request by allasm**

### CODE REVIEW

**Comment by allasm** [comment]
@antonkatz or @veronikaslc, please review

**Comment by veronikaslc** [comment]
Shouls [those](https://github.com/phenotips/phenotips/blob/5f747049e00f3a01867f66bf37c4db497a7ab740/components/pedigree/resources/src/main/resources/pedigree/pedigreeEditorParameters.js#L42-L46) be removed as well?

**Comment by veronikaslc** [comment]
And [this](https://github.com/phenotips/phenotips/blob/5f747049e00f3a01867f66bf37c4db497a7ab740/components/pedigree/ui/src/main/resources/PhenoTips/PedigreeConfiguration.xml#L69) line too?

**Comment by allasm** [comment]
@veronikaslc: yes and yes

**Comment by allasm** [comment]
Fixed all the things mentioned above and squished the commits so that there is only one commit for that issue. Please check and +1 if it can be merged now

**Comment by veronikaslc** [comment]
+1

**Pull request merged**
