### PR TITLE
PT-2749: Comments box is truncated when variant is added to a gene

### PR DESCRIPTION
**Pull request by veronikaslc**
Fixed

### CODE REVIEW

**Comment by veronikaslc** [comment]
@itaiGershtansky @AlexLapena please review/test

**Comment by itaiGershtansky** [comment]
+1

**Comment by AlexLapena** [comment]
+1

**Comment by marta-** [comment]
@veronikaslc Can we do "colspan='2'" for zygosity?

**Comment by veronikaslc** [comment]
@marta- I'm afraid "colspan='2'" for zygosity not helping much, as far as I tried.

**Pull request merged**
