### PR TITLE
PT-2100: Warn user when he tries to save gene/variant with empty key field.

### PR DESCRIPTION
**Pull request by veronikaslc**
Fixed. Gene and variant duplicate code refactored.

### CODE REVIEW

**Comment by marta-** [comment]
@AlexLapena can you re-test and re-review?

**Comment by AlexLapena** [comment]
Unable to save and view summary if the user deletes a variant after `Please enter a value` is displayed for that specific variant.

**Comment by veronikaslc** [comment]
Amended PR, @AlexLapena please, re-test and re-review.

**Comment by AlexLapena** [comment]
+1 @veronikaslc

**Comment by allasm** [comment]
ready to be merged?

**Pull request merged**
