### PR TITLE
PT-1794

### PR DESCRIPTION
**Pull request by a-gvo**
@itaiGershtansky @veronikaslc Please review.

### CODE REVIEW

**Comment by marta-** [comment]
Let's replace @buske, who's a bit busy this week, with @veronikaslc as the second reviewer.

**Comment by veronikaslc** [comment]
+1

**Comment by itaiGershtansky** [comment]
+1

**Comment by marta-** [comment]
@a-gvo Looks good, however you have unnecessary code duplication. Instead of **adding** a `delete` entry to the group of actions specific to `edit` mode, why not just **move** lines 1164-1166  outside the `view/edit` branching, to line 1173 (in the original file), right before 'Jump to..'?

**Comment by a-gvo** [comment]
@marta- Fixed and pushed. I should have been paying more attention, thank you.

**Comment by marta-** [comment]
great, thanks!

+1 @sdumitriu

**Comment by marta-** [comment]
@a-gvo Actually, if I can make another obnoxious comment :) : the code reads better if the initialization of `$canDelete` and its use are close together, so I'd move the initialization right before the `#if` statement that checks its value. In general, the code is much easier to understand and maintain if it flows naturally, no unnecessary jumps in logic.

**Comment by a-gvo** [comment]
@marta- moved as suggested :).

**Comment by marta-** [comment]
Final answer: +1 @sdumitriu

**Pull request merged**
