### PR TITLE
PT-2838: Hide consent warning of no sections to display in view mode.

### PR DESCRIPTION
**Pull request by veronikaslc**

### CODE REVIEW

**Comment by veronikaslc** [comment]
@marta- second warning is removed.

**Comment by veronikaslc** [comment]
How about showing warning only in edit mode then?

**Comment by sdumitriu** [comment]
Perhaps the issue and commit message should be changed to reflect the code.

**Comment by marta-** [comment]
@allasm anything against merging?

**Comment by allasm** [comment]
nope, +1

**Pull request merged**
