### PR TITLE
PT-3304 Underlines new patient button on hover

### PR DESCRIPTION
**Pull request by AlexLapena**

### CODE REVIEW

**Comment by AlexLapena** [comment]
@sdumitriu We have a CSS rule for it, however it seems to not want to work unless I create the a tag.

https://github.com/phenotips/phenotips/blob/79c2c7c4fbd47d4be9d335352e56f0bb71218520/components/skin/ui/src/main/resources/PhenoTips/Skin.xml#L871

**Comment by marta-** [comment]
@AlexLapena actually no, that rule would not apply to this element. It's for elements with `id="create-patient-record"`.

**Comment by AlexLapena** [comment]
@marta- I just noticed that ^^

**Comment by AlexLapena** [comment]
Fixed and rebased.

**Pull request merged**
