### PR TITLE
PT-2047

### PR DESCRIPTION
**Pull request by tmarathe**
Obstetric history integration tests

### CODE REVIEW

**Comment by sdumitriu** [comment]
Is this ready?

**Comment by tmarathe** [comment]
Yes, sorry, forgot to nominate for review. @meatcar, @mjshepherd please review!

**Comment by mjshepherd** [comment]
+1, but tbh I'm not too familiar with the front-end tests

**Comment by marta-** [comment]
@meatcar please review.

**Comment by meatcar** [comment]
looks good +1

**Comment by veronikaslc** [comment]
+1

**Pull request closed without merging**
