### PR TITLE
[add-selection-tools]: Added missing selection tools to the selection fields push dialog

### PR DESCRIPTION
**Pull request by veronikaslc**
Added "Select: All · None · Invert selection · Restore initial values" tools to the top of the push dialog.

### CODE REVIEW

**Comment by veronikaslc** [comment]
@allasm @itaiGershtansky please review

**Comment by marta-** [comment]
@veronikaslc With this change, the selection tools show up twice in the modal for pushing patients in bulk.

**Comment by veronikaslc** [comment]
Indeed, will correct by checking if selection tools already there.

**Comment by marta-** [comment]
@veronikaslc I think you should avoid duplicating the code for generating selection tools.

I've just committed to master (c0b0bff) a couple of small fixes that would prevent the existing export code from working in the single push dialog. Here's my suggestion on what to do next:
* Move the JS and CSS code related to export from the DBWebHomeSheet document ([1], [2]) either to the ExportPreferences document [3] or to the filesystem, since it's really not tied to the alldata table specifically
* Pull the (new) export JS and CSS extensions in the AllData document [4] to enable the bulk export UI 
* Pull the (new) export JS and CSS extensions in the PushPatient UIX [5] to enable the functionality that adds the selection tools. Also remove  the line which pulls the CSS from DBWebHomeSheet, because its only purpose was to use the export ui style for the push dialog.

[1] https://github.com/phenotips/phenotips/blob/master/components/navigation/ui/src/main/resources/PhenoTips/DBWebHomeSheet.xml#L177
[2] https://github.com/phenotips/phenotips/blob/master/components/navigation/ui/src/main/resources/PhenoTips/DBWebHomeSheet.xml#L777
[3] https://github.com/phenotips/phenotips/blob/master/components/export/ui/src/main/resources/PhenoTips/ExportPreferences.xml
[4] https://github.com/phenotips/phenotips/blob/master/components/navigation/ui/src/main/resources/data/AllData.xml#L64
[5] https://github.com/phenotips/phenotips/blob/master/components/patient-data-sharing/push-ui/src/main/resources/PhenoTips/PushPatient.xml#L1681

I hope this helps.

**Comment by allasm** [comment]
+1 to Marta's comments

**Comment by marta-** [comment]
Closing this. A new PR with the suggested implementation should be made.

**Pull request closed without merging**
