### PR TITLE
disabled jacoco in selenium functional-tests

### PR DESCRIPTION
**Pull request by JKereliuk**

### CODE REVIEW

**Comment by sdumitriu** [comment]
Who are you nominating for review?

**Comment by JKereliuk** [comment]
Review @DeanWay @meatcar

**Comment by meatcar** [comment]
:+1:

Also, their version number is interesting, combining the date and time of the release. They have one from 2011, the version is `0.5.4.201111111111`.

**Comment by meatcar** [comment]
@sdumitriu jenkins fails due to "no space left on device"

**Comment by sdumitriu** [comment]
@meatcar I'll fix that.

**Comment by sdumitriu** [comment]
Disk issues fixed.

**Comment by JKereliuk** [comment]
jenkins still fails to "no space left on device"

**Comment by sdumitriu** [comment]
Right, the disk issue was in a different place. Fixed that as well.

**Comment by sdumitriu** [comment]
This can be done [much simpler](https://github.com/phenotips/phenotips/blob/phenotips-1.1/pom.xml#L918).

And there's [another module](https://github.com/phenotips/phenotips/tree/master/components/navigation/tests) with functional tests, fix that one as well.

**Pull request merged**
