### PR TITLE
PT-3921: PhenoTips doesn't work with Java 11 on Mac

### PR DESCRIPTION
**Pull request by sdumitriu**

### CODE REVIEW

**Comment by buske** [comment]
Should it also be removed from https://github.com/phenotips/phenotips/blob/master/components/base-war/pom.xml#L449-L452 ?

**Comment by buske** [comment]
PhenoTips also doesn't build with Java 11 on Mac:

$ mvn clean install -Pquick
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:javadoc (generate-javadocs) on project jetty-log-writer: An error has occurred in JavaDocs report generation: 
[ERROR] Exit code: 1 - javadoc: error - An internal exception has occurred. 
[ERROR] 	(java.lang.NoClassDefFoundError: com/sun/tools/doclets/Taglet)
[ERROR] Please file a bug against the javadoc tool via the Java bug reporting page
[ERROR] (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
[ERROR] for duplicates. Include error messages and the following diagnostic in your report. Thank you.
[ERROR] java.lang.NoClassDefFoundError: com/sun/tools/doclets/Taglet
```

**Comment by sdumitriu** [comment]
Yep, I know about compiling not working, but that's a bigger change.

**Comment by sdumitriu** [comment]
@buske Committed some more changes, please re-test (building with Java8, running with Java11).

**Comment by buske** [comment]
Works! I did observe an unfamiliar warning on startup though:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.SerializationMembers (file:/Users/buske/dist/phenotips/phenotips-standalone-1.5-SNAPSHOT/webapps/phenotips/WEB-INF/lib/xstream-1.4.8.jar) to method java.util.concurrent.ConcurrentLinkedQueue.readObject(java.io.ObjectInputStream)
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.SerializationMembers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
As well as more familiar warnings:
```
2018-12-21 11:09:29,012 [http://localhost:8080/jsx/PhenoTips/Widgets?language=en&docVersion=1.1] WARN  o.a.s.c.SolrResourceLoader     - Solr loaded a deprecated plugin/analysis class [solr.SynonymFilterFactory]. Please consult documentation how to replace it accordingly. 
2018-12-21 11:09:59,797 [http://localhost:8080/PhenoTips/CreatePatientRecord] WARN  o.a.s.h.l.XMLLoader            - Using document boost: 1.0 != 1.0 will not be supported anymore in 7.0. Please index scoring factors into a separate field and combine them with the main query's score using function queries.
```

**Pull request merged**
