### PR TITLE
PT-3481 and PT-3501 (BOADICEA import and export, cancer data extension)

### PR DESCRIPTION
**Pull request by allasm**

### CODE REVIEW

**Comment by sashaandjic** [comment]
It's no longer freezing, however it still doesn't work.

Step to produce:
- create new family by importing json file from the JIRA issue
- export into BOADICEA
- import BROADICHEA file (txt file attached to JIRA issue)
- error msg pops up
screen shot 2017-10-31 at 11 14 51 pm

**Comment by sashaandjic** [comment]
I'm not sure how to test PT-3501

**Comment by allasm** [comment]
Fixed, and discussed testing with Sasha

**Comment by allasm** [comment]
re: ages: this is expected, cause by the limitation of the BOADICEA format

**Pull request merged**
