### PR TITLE
Fix for ListController export with deleted objects

### PR DESCRIPTION
**Pull request by buske**
- Added test suite for GeneListController (based on @veronikaslc's VariantListControllerTest in PR) (PT-2144)
- Added test for VersionController (PT-2144)
- Added null test on response of `getXObjects` in VersionController and GeneListController (PT-2143)

### CODE REVIEW

**Comment by buske** [comment]
@veronikaslc @antonkatz please review. This is targeted for 1.2.

**Comment by buske** [comment]
@sdumitriu should this be against master or stable-1.2x?

**Comment by antonkatz** [comment]
+1

**Comment by allasm** [comment]
I also looked at the commit, +1.

**Comment by allasm** [comment]
BTW, branch name is incorrect, it should be PT-2143, not PT-2163. Because of this PT-2163 is linked to these commits even though it is not related at all.

**Comment by buske** [comment]
@allasm Oh no, sorry!

**Pull request merged**
