### PR TITLE
Move edit button to the header of the variant grid.

### PR DESCRIPTION
**Pull request by veronikaslc**

### CODE REVIEW

**Comment by marta-** [comment]
FTR, these changes don't actually move the button to the header. Instead, they modify the look and placement of the button to be more consistent with the delete button that is displayed above it.

I haven't tested the changes myself, but I've reviewed them with Veronika so +1 from me.

**Comment by marta-** [comment]
@a-gvo @AlexLapena please review and test. Thanks!

**Comment by a-gvo** [comment]
+1

**Comment by AlexLapena** [comment]
+1 also

**Pull request merged**
