### PR TITLE
PT-3485:  Permissions dialog: clicking on the new owner field should automatically select Transfer ownership to another user or group

### PR DESCRIPTION
**Pull request by veronikaslc**

### CODE REVIEW

**Comment by veronikaslc** [comment]
That would be strange, because we decided to disable input field until user selects corresponding radio button.

**Comment by sdumitriu** [comment]
Right... It doesn't make sense to have the input disabled. Make the input always enabled, and when it gets clicked, also select the associated radio button.

**Comment by veronikaslc** [comment]
We decided to leave PR like that. The JIRA issue name changed accordingly implementation.

**Comment by veronikaslc** [comment]
@sashaandjic this one was decided to be implemented as originally planned, ready to test

**Comment by veronikaslc** [comment]
@sdumitriu fixed

**Pull request merged**
