### PR TITLE
PT-2565, PT-2566 fixed.

### PR DESCRIPTION
**Pull request by williehwc**
(PT-2583, the name of this branch, is closely associated with PT-2566 and was fixed by Marta. The PT-2566 fix extends the PT-2583 fix to paragraphs and divs)

### CODE REVIEW

**Comment by williehwc** [comment]
@itaiGershtansky please review

**Comment by itaiGershtansky** [comment]
Finer commit granularity (for next time). Other than that, +1.

**Comment by marta-** [comment]
Please make separate PRs for issues with independent fixes.

**Comment by itaiGershtansky** [comment]
The consent texts appear on a line below the checkbox, because of the <div>-s that are not removed. They cannot all be removed, but those who cause that line break should.

**Comment by williehwc** [comment]
@itaiGershtansky The consent identifier (label) are one-liners that should not have divs, but they are rendered with divs using XWikiDocument.display. The divs cause the consent identifiers to appear below the checkbox, so they should always be removed. The consent descriptions have divs, but they are kept because they should appear below the checkbox as expected.

**Comment by williehwc** [comment]
To-do: Remove div tags from consent labels, since PhenomeCentral (not PhenoTips, apparently) inserts div tags in consent labels.

**Comment by allasm** [comment]
Maybe the difference between PhenomeCentral and PhenoTips is that in PT you manually entered the label, while in PC we use translations, which are rendered differently?

**Comment by williehwc** [comment]
This pull request will be closed; two new pull requests will be made that separate the fixes.

**Pull request closed without merging**
