### PR TITLE
PT-1044: Deep subterms will automatically expand when selecting YES

### PR DESCRIPTION
**Pull request by mjshepherd**

### CODE REVIEW

**Comment by mjshepherd** [comment]
@itaiGershtansky  @danielpgross

**Comment by sdumitriu** [comment]
I already implemented this in d52e5adead3e700ad499273dc70e6665997814fa

**Comment by marta-** [comment]
Sorry @mjshepherd , didn't realize this was already done. @sdumitriu should have mentioned it.

**Comment by sdumitriu** [comment]
Well, I did fix it but only for phenotypes displayed in the main patient record. The ontology browser ("Browse related terms") doesn't expand with my fix. @mjshepherd your fix works in the obrowser as well, right?

**Comment by sdumitriu** [comment]
One thing I don't like is that it adds a light dependency between the obrowser and the ynpickers widget. The way the code is organized now, the base obrowser doesn't display ynpickers, just a plain checkbox. And this is how it still work, for example, on the "Browse all" page, when selecting phenotypes to filter on. So, things to check:

- does it autoexpand in the "Browse related terms" dialog?
- does it still work, without throwing any JS errors, in the "Browse related terms" dialog when used in the "Browse all data" page?

**Comment by mjshepherd** [comment]
@sdumitriu TBH I completely forgot about the browse related terms. It works now. No errors are formed. I agree with you that the dependency is not great.

**Comment by marta-** [comment]
@itaiGershtansky @veronikaslc please review. @danielpgross too, if you have time.

**Comment by veronikaslc** [comment]
+1, works.

**Pull request merged**
