### PR TITLE
Issue 1654#2

### PR DESCRIPTION
**Pull request by itaiGershtansky**
@allasm, @danielpgross, please review

### CODE REVIEW

**Comment by danielpgross** [comment]
:+1:

On a non-technical UI point, I think it's worth considering the symbol used for "Other". The diamond symbol seems to consistently represent "unknown gender" or "unspecified gender" in pedigree drawing standards, but "other" has a distinctly different meaning, like just like "null" is different from "undefined". Maybe there should be an "O" overlaid onto the diamond. +@sdumitriu and @allasm for feedback.

**Comment by marta-** [comment]
@CourtneyHum any suggestions on the symbol to use in the pedigree when the gender is "Other"?

**Comment by CourtneyHum** [comment]
If going by the standard pedigree nomenclature 

"The Pedigree Standardization Work Group continues to recommend that the male or female symbol be used to define the phenotypic gender, with the karyotype noted below the symbol, when known...A diamond can be used when it is not clinically relevant to assign gender"

image

**Comment by CourtneyHum** [comment]
I don't know if this is possible, but could the default be a diamond for someone with gender "other" but either male or female selected in the pedigree editor by the clinician, without changing in the Patient Information section?

**Comment by marta-** [comment]
Could the different options listed in https://github.com/phenotips/phenotips/issues/1654#issuecomment-114951789 be each mapped to a gender symbol?

**Comment by CourtneyHum** [comment]
image

It's not straightforward. 
1. a) i) female
        ii) either
        iii) either
        iv) either
    b) i) either

etc...

With most of these DSD's there is a spectrum of severity depending on the effect of the mutation so the decision to raise an individual as a male or female is difficult and not always predictable based on the condition.

**Comment by CourtneyHum** [comment]
@bgallinger I'd love to discuss this with you because the issue is getting more and more complicated

**Comment by CourtneyHum** [comment]
In The Practical Guide to the Genetic Family History

"A diamond can also represent persons with congenital disorders of sex development in which chromosomal, gonadal, or anatomic sex is atypical."

**Comment by marta-** [comment]
So should there be a note under the diamond stating what kind of "other" it is? would that make things clearer for everyone?

**Comment by CourtneyHum** [comment]
Yes the user should write in the karyotype and the diagnosis

image

**Comment by CourtneyHum** [comment]
Other
- karyotype ____________ (anything with a Y is coded as male for growth charts)
- phenotypic sex M | F | Neither (to determine pedigree symbol)

**Pull request merged**
