### PR TITLE
PT-3282: Allow pushing/exporting/importing medical reports

### PR DESCRIPTION
**Pull request by sdumitriu**
Done

### CODE REVIEW

**Comment by sdumitriu** [comment]
@sashaandjic @AlexLapena Can you check this quickly please?

**Comment by sashaandjic** [comment]
it doesn't work for me

**Comment by AlexLapena** [comment]
Same, push isn't working for both multi-patient and single patient.

**Comment by sdumitriu** [comment]
Where are you pushing? Only the same instance would be able to receive the data.

**Comment by sdumitriu** [comment]
How about JSON import/export, REST?

**Comment by AlexLapena** [comment]
Pushing to the same instance. Testing JSON now, then REST.

**Comment by AlexLapena** [comment]
JSON import/export works, but the file itself looks a little scary with the long value for content field.

**Comment by sdumitriu** [comment]
Indeed, found the problem with push, will fix.

**Comment by sdumitriu** [comment]
@sashaandjic @AlexLapena Push should work now, please retest.

**Comment by sashaandjic** [comment]
I'm unable to build.

**Comment by marta-** [comment]
@sashaandjic what error are you getting?

**Comment by sashaandjic** [comment]
@marta-  I'll send you entire log on Slack

**Comment by marta-** [comment]
@sdumitriu the tests appear to be failing.

@sashaandjic just run `mvn clean install -Pquick` for now to skip the tests until they are fixed.

**Comment by sashaandjic** [comment]
tested single JSON import, multiple JSON import and push all patients with one or two med reports. no issues found.

**Pull request merged**
