### PR TITLE
PT-1366: The vocabulary reindexing operation should not leave the system in a bad state at any moment

### PR DESCRIPTION
**Pull request by veronikaslc**

### CODE REVIEW

**Comment by veronikaslc** [comment]
the only problem is to delete one file in temp directory `java.io.IOException: Unable to delete file: ...\PhenoTips\solr\hpo_temp\data\spellchecker\_0.cfs`
 
windows displays `File In Use` error `... the file is open in Java(TM) Platform SE binary`
  
other than that reindexing should work

**Comment by allasm** [comment]
what happens if that `File IN Use` error happens? A junk file is left or re-indexing still fails?

**Comment by veronikaslc** [comment]
Nothing happens, directory is cleaned after successful reindexing, so just one file is left.

**Comment by sashaandjic** [comment]
tested

**Comment by veronikaslc** [comment]
rebased

**Comment by veronikaslc** [comment]
@sdumitriu if `reindex()` is identical for all three, can I move it to `AbstractSolrVocabulary`?

**Pull request merged**
