### PR TITLE
PT-2706: Automatic phenotypes do not appear in differential

### PR DESCRIPTION
**Pull request by mjshepherd**

### CODE REVIEW

**Comment by mjshepherd** [comment]
@antonkatz @veronikaslc please review

**Comment by antonkatz** [comment]
+1. Though that code has finicky flow, so I expect bugs.

**Comment by marta-** [comment]
@antonkatz if nominated reviewers also tested the change whenever possible in addition to just reading it, we migh end up with better quality code and fewer bugs...

**Comment by veronikaslc** [comment]
+1

**Pull request merged**
