### PR TITLE
Prefer "true" and "false" to calling Boolean.toString with a constant

### PR DESCRIPTION
**Pull request by alexhenrie**
This is mainly just to simplify the code base, although it may also offer a slight performance improvement.

### CODE REVIEW

**Comment by sdumitriu** [comment]
This will trigger checkstyle exceptions, duplicate strings are not allowed. We could change the checkstyle rules to allow `true` and `false` as special strings.

**Comment by marta-** [comment]
The checkstyle rules are like that for a reason. This particular rule prevents errors caused by typos in the strings. It happens surprisingly often.

Bottom line: the checkstyle rules will not be changed; however, we are open to changes with the same purpose that do not imply repeating constant strings.

Thanks!

**Comment by sdumitriu** [comment]
And I'm not sure that this really has a performance benefit. If not the compiler, the JVM JIT optimizer can easily detect that this method call always has the same effect and just replace it with the constant.

**Comment by sdumitriu** [comment]
Ran a quick test, using string constants is about 25% faster than `Boolean.toString` calls, but the time gained is insignificant. 10M calls take less than 100ms, and the code optimized is not that critical for performance.

**Comment by sdumitriu** [comment]
Actually my test was flawed, the second time also included the time needed to allocate the buffer. After correcting it, there is no difference between the performance of either method.

Given that the current code is easier to understand, it should stay as it is.

**Pull request closed without merging**
